platform:
- x64

configuration:
- Release

version: 1.0.{build}
os: Visual Studio 2017
clone_depth: 1

install:
  - appveyor DownloadFile https://github.com/xpol/luavm/releases/download/0.5.4/LuaVM-0.5.4-vs2017-x64.exe
  - LuaVM-0.5.4-vs2017-x64.exe /verysilent /dir=C:\luavm

before_build:
- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
- cmake -S . -B build -G "Visual Studio 15 2017 Win64" -DLUA_LIB_NAME=lua51 -DLUA_LIB_PATH="C:\luavm\versions\5.1" -DLUA_INCLUDE="C:\luavm\versions\5.1\include"

build_script:
- cmake --build build --config Release
