name: lua-poco linux build

on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:
    build-lua-poco-5.3:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: install dependencies
          run: sudo apt install -y cmake liblua5.3-dev libpoco-dev
        - name: cmake
          run: cmake -DCMAKE_BUILD_TYPE=Release -DUSE_EMBEDDED_POCO=OFF -DLUA_INCLUDE=/usr/include/lua5.3/ -DLUA_LIB_NAME=lua5.3 ..
        - name: make
          run: make install
          
    build-lua-poco-5.2:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: install dependencies
          run: sudo apt install -y cmake liblua5.2-dev libpoco-dev
        - name: cmake
          run: cmake -DCMAKE_BUILD_TYPE=Release -DUSE_EMBEDDED_POCO=OFF -DLUA_INCLUDE=/usr/include/lua5.2/ -DLUA_LIB_NAME=lua5.2 ..
        - name: make
          run: make install
          
    build-lua-poco-5.1:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: install dependencies
          run: sudo apt install -y cmake liblua5.1-dev libpoco-dev
        - name: cmake
          run: cmake -DCMAKE_BUILD_TYPE=Release -DUSE_EMBEDDED_POCO=OFF -DLUA_INCLUDE=/usr/include/lua5.1/ -DLUA_LIB_NAME=lua5.1 ..
        - name: make
          run: make install

